workflows:
  react-native-android:
    name: React Native Android
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build and test
        script: |
          npm run build
          npm test
    triggers:
      - event: push
        branch: master
