workflows:
  my_workflow_name:
    name: collegeProjectApp
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build and test
        script: |
          npm run build
          npm test
    triggers:
      - event: push
        branch: master
